### PR TITLE
Update Plugin.php

### LINKED ISSUE #34: Location not updating from frontend form
Hi, 
I have user plus installed everythings works great the only thing that was causing me trouble was updating country and state from frontend user profile page. 

After I've put this part of code for country
`$model->addFillable(['country_id']);` 
into the `Plugin.php` in the `extendUserModel()` function after implement declaration  `$model->implement[] = 'RainLab.Location.Behaviors.LocationModel';` it starts working. Not quite sure if this is a bug with this plugin or with the Location, or if I am doing something wrong here

### PR DESCRIPTION
**Pull request by TimFoerster**
fixes #34

### CODE REVIEW

**Comment by bennothommo** [comment]
@TimFoerster thanks for this fix, however, I think the issue actually lies with the Location plugin. This plugin makes the `User` model use the `LocationModel` behavior, as [seen here](https://github.com/rainlab/userplus-plugin/blob/master/Plugin.php#L63). This behavior is supposed to already make the `state_id` and `country_id` fillable, as [this code block](https://github.com/rainlab/location-plugin/blob/master/behaviors/LocationModel.php#L33-L42) shows. I suspect that something is preventing this from running.

**Comment by TimFoerster** [comment]
https://github.com/octobercms/library/blob/b2907902f5a3b121a291f1ba0d045461e4d6fb55/src/Auth/Models/User.php#L58
is setting a guarded field
https://github.com/rainlab/location-plugin/blob/master/behaviors/LocationModel.php#L33-L42
does not set the values, because:
> The only case that is not supported is if the developer overrides both `$fillable` and `$guarded`. This seems acceptable to me, since the docs explicitly state:
>>   Of course, you should use either $fillable or $guarded - not both

https://github.com/rainlab/location-plugin/pull/53

So the rainlab.User plugin implement guarded and fillable ...

Related (old) issue:
https://github.com/rainlab/user-plugin/pull/33

So either set `$guaded = ['*']` or `$guarded = []` in the user model.

**Comment by bennothommo** [comment]
@TimFoerster you're correct. So, the issue is:

- The `October\Rain\Auth\Models\User` class defines a `$guarded` property, making everything except for those fields writable.
- The `RainLab\User\Models\User` classes, which extends the model above, then defines a `$fillable` property, which reverses this and makes only those fields writable.
- The `RainLab\Location\Behaviors\LocationModel` class only makes the required state/country fields fillable if `$guarded` is set to `['*']`.

So the simple fix would be to set `$guarded` to `['*']` in the `RainLab\User\Models\User` class, as this is already implied by it setting the `$fillable` property anyway. Would you care to submit a PR with that to the User plugin?

**Comment by TimFoerster** [comment]
https://github.com/rainlab/user-plugin/pull/434

**Comment by bennothommo** [comment]
Closing in favour of rainlab/user-plugin#434.

**Pull request closed without merging**
